using System.IO;
using System.Reflection;
using System.Text;
using SharpCompress.Common;
using SharpCompress.Crypto;
using SharpCompress.Readers;
using SteamSentinel.Core.Inspection;

namespace SteamSentinel.SelfTest;

internal static partial class Program
{
    private delegate void V020BlakeUpdate(ReadOnlySpan<byte> bytes);

    private static void TestV020RarIntegrityPrimitives()
    {
        // The empty and 64-byte values are official, unkeyed BLAKE2sp KATs:
        // https://github.com/BLAKE2/BLAKE2/blob/master/testvectors/blake2-kat.json
        // The 512/513-byte values were independently emitted by signed RAR 7.23
        // with -m0 -htb on byte[i] = i mod 256. They cross the full stripe boundary.
        (int Length, string Hash)[] vectors =
        [
            (0, "DD0E891776933F43C7D032B08A917E25741F8AA9A12C12E1CAC8801500F2CA4F"),
            (64, "52603B6CBFAD4966CB044CB267568385CF35F21E6C45CF30AED19832CB51E9F5"),
            (512, "322CE06CC141A0B3D89BCDCFCB385975DBCA56E5719A78C34000FCEC2E15B55D"),
            (513, "1336628C7F1541C7815FC0FF1FB5DFB07A85CF5A17A2872A3CE4B322D4A03D0B")
        ];
        Type blakeType = typeof(ArchiveIntegrity).Assembly.GetType("SteamSentinel.Core.Inspection.RarBlake2sp", true)!;
        foreach ((int length, string expected) in vectors)
        {
            byte[] input = Enumerable.Range(0, length).Select(i => (byte)(i & 255)).ToArray();
            byte[] Hash(int[] chunks)
            {
                object blake = Activator.CreateInstance(blakeType, nonPublic: true)!;
                V020BlakeUpdate update = blakeType.GetMethod("Update", BindingFlags.Instance | BindingFlags.NonPublic)!
                    .CreateDelegate<V020BlakeUpdate>(blake);
                int position = 0, chunk = 0;
                update(ReadOnlySpan<byte>.Empty);
                while (position < input.Length)
                {
                    int count = Math.Min(chunks[chunk++ % chunks.Length], input.Length - position);
                    update(input.AsSpan(position, count)); position += count;
                }
                return (byte[])blakeType.GetMethod("Finish", BindingFlags.Instance | BindingFlags.NonPublic)!.Invoke(blake, null)!;
            }
            Check($"0.2.0 BLAKE2sp {length}字节独立向量与不规则分块一致",
                Convert.ToHexString(Hash([1024])) == expected && Convert.ToHexString(Hash([1, 63, 65, 127, 2])) == expected);
        }

        // These 149-byte stored archives were independently generated by signed
        // RAR 6.24 (-ma4 -m0 -pPASSWORD), then passed signed UnRAR 7.23 `t`.
        // Plaintext is only the inert string below. No member is ever executed.
        // Generator source: https://www.win-rar.com/fileadmin/winrar-versions/winrar-x64-624.exe
        // Installer SHA256: 377ABC9D367E61CB5C4761BF48DCFDF5BCD3822F303E0F972D7F4C8295A2EA79
        // The long password exercises historical sha1_process_rar29 mutation;
        // the non-ASCII password exercises actual UTF-16LE, not UTF-8 widening.
        (string Name, string Password, string Archive)[] rar4Vectors =
        [
            ("短密码", "Inert-624",
                "UmFyIRoHAM+QcwAADQAAAAAAAABTjXQklDoAQAAAADIAAAACoC9fZnOpJl0dMA0AIAAAAGluZXJ0LWtkZi50eHSd2tzjMy6yLwDwcY914rRPEhpnmj4gc2aI5D4nUmEFqlIwtTe5tzglghCVpQxhm/loh1QFR74s0NIIECPL9699QG5OBt1nU4VF7zZJbcQ9ewBABwA="),
            ("长密码", "SteamSentinel-RAR4-Long-Password-0123456789-abcdef",
                "UmFyIRoHAM+QcwAADQAAAAAAAACBa3QklDoAQAAAADIAAAACoC9fZnOpJl0dMA0AIAAAAGluZXJ0LWtkZi50eHQMBSI7nNGHBgDwcY91Jb2tIMUF2Rt2wHP041b/3cau/qJzRLc8Ub7Bvt3S+vd7opTuwsbgNzJELbaY3BhGADxMwmrRhHmAkBWMR22r4cQ9ewBABwA="),
            ("非ASCII密码", "密码-Äé-日本-624",
                "UmFyIRoHAM+QcwAADQAAAAAAAABL1HQklDoAQAAAADIAAAACoC9fZnOpJl0dMA0AIAAAAGluZXJ0LWtkZi50eHRV/7U9FTN2hADwcY91hLi0ui7fa5eFaPfZliJ4+hO787wyuGhtVLj2pSXSoIkAp9oAWWszX7pNvAj+EqtD4de3Bhvor7yZNg1qwuYs78Q9ewBABwA=")
        ];
        byte[] plaintext = Encoding.UTF8.GetBytes("SteamSentinel RAR4 KDF fixture: inert text only.\r\n");
        foreach ((string name, string password, string archive) in rar4Vectors)
            Check($"0.2.0 RAR4官方{name}固定密文通过KDF与内容校验",
                V020RarFixedContent([Convert.FromBase64String(archive)], password, plaintext));

        // RAR 6.24 additionally generated old .rar/.r00 volumes with -vn -v768b;
        // it rounds the first physical volume up to 1000 bytes. The split ciphertext
        // boundary is not AES-aligned, so independently resetting CBC cannot pass.
        byte[][] split =
        [
            Convert.FromBase64String("UmFyIRoHALLvcwEBDQAAAAAAAAAe13QmlDwAhAMAAAEEAAACVOoAqPqpJl0dMA8AIAAAAGluZXJ0LXNwbGl0LmJpbhQRlO1tTVjiALDajH+RnWrep0Le3+L3UyEM3lZ+WNYvHeZSGpTKPY1VO1p2de1z4PJITRNqXu2eEZr6JvvBtLGlKAzd7+vJod2eF9xUvNTP/qM/h7bVGg24tbyuhLwd8J69BfHPC7hGzq7F3WFqQR89fShIYKECYh40q+9QucGVtE8o7Gs2Dsdh7vX7jQwDGpqToWwGLL8tymYF/WqWA7WCLl61m5ua4fck/L/nxTSb6YbJuxiFD16Mrsp9buHGgKDHBJ2FKDZsmBTPYns3X9TaqJRQMPnC+Qk3V3xRZ9LAxsKat/Olu8/kmaUgXp5eI03zv+Baagm4KJO/w+7Ppa43FVQOGL7KVdbNADLHN1KBn7IFfG/fXG8DuCVx7wN6Njl4bIruFR8SqA99mY3gMsi4wKAMIo3ztBcl2aihzjO/t/Z4JSVr+71MoOeFlw8uKGfVh1bHEbrXC8ns2MV+oheB/FYC1CYaGEHf+rmfVDv9C/1O+1sVK+GGvCYyGE/2WUosn2U6tin7jIYk/lna98m6BGKiaQVccDC4EYHZNXSPmUdFOk5skbVpUNrJV1rhKecDO8OvK6DpkyR+ihyh7kRQ43zi46MZ3qDndPz2hy1BaaYNmvNgxAhqvz6/qI3MT+YvCtjNftj30eal5yRqsERWunD6rrODV5lHndE4OYwZQjhUKoMZnKPaPrIwA5eM1du4i7N+KV+/lMQ0lNbEMoUaJmg79Fu2CG3tm5062ecJ8HV7e98VvTPBu4K+ASoWyTRn5UZBu23m+85HZ5QScrTdMewUMK/9E/ZHMYxJJy781GJaJDHYjL3zWqwAx7UU2ZMMQiUAey0B3sXpAnjo0tGel/K4aDHNsQAMPghvVebD8PV20AgFMptzYrdf537OwkFneuxw6XLaPfOfcVhSE1VQ58wqu6tE2mTWLDHhDxn82mOAieYhti8UHtf8YnKeM1moXKSpx+i8fDJHhlLQJpqWGpvYdQfBzVVgx/sFvqMUWlF+F0J5qY93x0qPFe6IYvGrYl7edc3r6mYa/A6/5Eqrcvl5E1rPjkJ2ANMn+lGors7nL/QRu6cXZ+F3qXIrKL0Sz04jKUPTh+rQJIskIyH0nEc+Gc8S2Ftnd00iqUZv/muiXvxKeLtlSQf8xppQZ6insPD+rHEs0KjS4FqMbfxqvLfpA2ifZhlGAi+5H84mEE8wwiA/ZQLL4SjLwnWFl+KQFHsPQBQA2rDXnwAAAAAAAAAAAA=="),
            Convert.FromBase64String("UmFyIRoHAPH7cwEADQAAAAAAAADcSHQllDwAjAAAAAEEAAACPGG4APqpJl0dMA8AIAAAAGluZXJ0LXNwbGl0LmJpbhQRlO1tTVjiALDajH9Pt2or1AX+AbkMXsqUuLE8KRLdP1zI/+jTfZd9nrR3KcX9YAuG4KtrC5xW8N2ID3wSJGgTi1MRtQYRGIcCtgxM7SH5bJ4aJOdpcKHoRScmOsAdjM/uZLmCgSk4A0szllVZ/18Z2MnrLMnyK6dR44s2bpT2lPAMuAgQFqsZP7pwJ2vIXCj15r7tM+zHHvozew5AFAACjFNCAQAAAAAAAAAA")
        ];
        Check("0.2.0 RAR4官方加密旧r00二卷跨AES分组保持连续CBC",
            V020RarFixedContent(split, "Inert-624", Enumerable.Range(0, 1025).Select(i => (byte)(i & 255)).ToArray()));

        foreach ((string name, string password, string archive) in V020Rar4HeaderVectors())
        {
            byte[] bytes = Convert.FromBase64String(archive);
            Check($"0.2.0 {name}官方加密文件名与原始内容完整校验",
                V020RarFixedContent([bytes], password, plaintext, requireEncryptedHeader: true));
            Check($"0.2.0 {name}错误密码不能通过加密头校验",
                V020RarFixedRejects([bytes], "definitely-wrong-inert", plaintext));
            byte[] damaged = bytes.ToArray(); damaged[28] ^= 1;
            Check($"0.2.0 {name}加密头篡改被拒绝",
                V020RarFixedRejects([damaged], password, plaintext));
        }
        var headerSplit = V020Rar4HeaderSplitVector();
        Check("0.2.0 RAR4官方长非ASCII密码加密文件名二卷连续解码",
            V020RarFixedContent(headerSplit.Volumes, headerSplit.Password, headerSplit.Plaintext, requireEncryptedHeader: true));
    }

    private static (string Password, byte[][] Volumes, byte[] Plaintext) V020Rar4HeaderSplitVector() =>
    (
        "SteamSentinel-RAR4-密码-Äé-日本-0123456789-abcdef",
        [
            // Signed RAR 6.24: -ma4 -m0 -vn -v768b -hpPASSWORD. Signed UnRAR 7.23
            // independently passed `t`; both original volume headers remain encrypted.
            Convert.FromBase64String("UmFyIRoHALPmc4EBDQAAAAAAAACmaE3onsnb7FZAJyeKcQUjkl9Om5yJDZmEUFzOzPddwZ18/KiZ1k/8tonD8Jeylb+v3Ogdj9x1ArmDxncyhj37PNB7viubPwq1j3RVOuSGKpkeVdhs/SPToN4cusPJoeqaTO8TLll+sW8o/MW67o1pKSkTRGBAggY9h7JeA6SSRW+ytHoLfeKFeZarHniBB43gbaXo628m48hKWFFDr2RAfH6XS6O/cAW38jRj3yvW0ltV6gmHgQcjeMvVHdoXTrGpNztvYmtZQroSbVO+bab998pIMCwWECJ8aoDPkAKq4OZRoVAcoUA4Wdqk+bU4+BUm9e+jUt91KaZwpF9Ih4CGfBnmO7lRS7ChpAUfIlsRoO9W9uM4O52oaupf+rJo85XzkQzPiQLRJFoLwuxtXK/oXYPVNCQnGjvUGlyncx4luTDFaGENDNzAX8hwV6Z/RnJMHNxneLOUPBIhFpnMPk1TbbAMH4CzX/NiNMDIhBOwliyLdWEEez2frvwsd4ZK4QqOehNr9FgUnHEpZFXgixlia19hnAGW01P/TK8Pd5kGicPas2hXdIOXXI2l14TeRn8ZvAbt/f6Amfpdte+q0OO6zsjJAiFx3ugxuopOV/qEUOobx8PCMMPOONmgoCy30EUha2dEiOduBXUPjH/egONhER1r5T/PiNP36ASd4Ivls1BYcS3jJBHNG3vrAIfTU672XjuGLQ+ncfDwG10D0GS+D2GfwdY+NJfwcNz8IkS7ANckrmzErz2J1htyd9KUeme19jiv6WGVMpnWDc0ck9xPUt/kTHl4vMIQukBvoolgzPEP4Is6NJqkPcDoq6bmjqUsd7I+R8B7/sSJ9ulESvM5k+ATkp4/JMjTHt6baDSjgtDVai19RsE0C0knY+hnVsFpJG/xq1Cn+pM3Id7cPtocfFSodA/3jWoxFWAioq8f+E1NRaliyKOgv9LWhTnt2sIc1aBSOaljEbHswCzFBAeULkBAUcz3/y6IP3DMZdhY/3xfn4IH8DBP7Gouttexyv/jjlo5ZdnTcJguU1C7nL2NmexMxVAPVnLo0F2xQSUtwAxQ3Gzwbu/25PBpqUj679EBEExHmp/ooDRwIumr79+WABgzAlrazD1ye62xiC01ukjy+QM27beoweG2Eo9BSL+zboihVrrfeQ3SX+t1Pm2Pq6WsDgojbYsFugHMgPyZ8vOQy0LriMQzfMUM9Oxom74zxeSCpPspOIRSKpgvBoIx8eY/S4IK4yrpM31UpmhN6J7J2+wgxVtlfzqyro568XFtg+x/XboNHjEtz7SuMta+CwMgyA=="),
            Convert.FromBase64String("UmFyIRoHAPDyc4EADQAAAAAAAACmaE3onsnb7IIWpXOKtbgrOJq1DwTcgGtWgt2TrN3Ioi84ZF6oyUsqMGxwzgTd4ffb4jF/LPv7IBmPYbM+Lhi+4BlDhP8mj9BL4K77DR6oYEH6Gpmr9QA3oPclfnQiA1p5Exk3SYtG45XiPf2/Vuj+vtZLz05EJ7TzbBcCzyWgGmJjdZTjukbtNoUpVqD9oeRz6bzX3JIKL4Cwt2w8/UufKDZX+A66yq7fQ5kojCimd/oi2W3heGVL52hurh5iYtJ0ifkhazqjXsr4StQ44jNQh+wR0B5eq7iDwWov+6YGrGd98ayAoK7ealdxFNVghm+E6fHypmhN6J7J2+z8ZckmwQl/gXJ1cCuljnj181Y90I0yx2Pa2F7x7XIwyg==")
        ],
        Enumerable.Range(0, 1025).Select(i => (byte)(i & 255)).ToArray()
    );

    private static (string Name, string Password, string Archive)[] V020Rar4HeaderVectors() =>
    [
        // Same signed official RAR 6.24 provenance as the data-encryption vectors;
        // generated with -ma4 -m0 -hpPASSWORD and independently checked by UnRAR 7.23.
        ("rar4-hp-short.rar", "Inert-624",
            "UmFyIRoHAM6Zc4AADQAAAAAAAACDTRPfvuuhfKkcrqVWeZDwUEMjcHUBoXVCmX0WDhuLnJ+ZhfkjsBhLy/g9H/qEq5mc9AjrWabZCaTm3hTryq0HJWDS8vAEFV6zQXiokXcbcmHhhbEpPxO/wqeZ9Ml/D5+4XTGGq5Wh8NgcJMsiLwkQoTHAo92oefJOwyG8dvObCb8BgIMzvprWg00T377roXzhgoIAMlew5U8f7PhQ0EiU"),
        ("rar4-hp-long.rar", "SteamSentinel-RAR4-Long-Password-0123456789-abcdef",
            "UmFyIRoHAM6Zc4AADQAAAAAAAABtlBpgwcE1duZn6ZqzG1gCgCkJSp0+Coa/m5nNv1jbItpwYsMNph/n3m4BmBTqV5rKAX9qQ57EhrraD3q9tHHQISCYr5e+HJpAAY4ejKF7Wp9d6LszuXytHADd6MYbVDgeRdyhcOnP/7uCvk87aEMLAC7sC9pxeo8gxFpQB5QKks29I+3UxTUFbZQaYMHBNXb/2nNrmY2wxH5pcAOHSsGF"),
        ("rar4-hp-unicode.rar", "密码-Äé-日本-624",
            "UmFyIRoHAM6Zc4AADQAAAAAAAADdpB9+F7jzb9CtGb1NAlgCfLNXZwHXAsgxN8K9DHQ2kqO2oJ63ljNIcV5Zgwb0VWB9blojFL8KXpRmr/HE/AxlScbeWK6afej692lrOJTcBXKKjDrPmGkJOOs30lmyUJ/A24lsZrpgJBa6XX44SrQTCXpuekH0VTeOi7j4Y8IRd0LnHLx3ibmI3aQffhe4828A7jEb462VFD5GW/rlVamM")
    ];

    private static bool V020RarFixedRejects(IReadOnlyList<byte[]> volumes, string password, byte[] plaintext)
    {
        try { _ = V020RarFixedContent(volumes, password, plaintext); return false; }
        catch (ArchiveVolumeException ex) { return ex.Reason == ArchiveVolumeStatus.InvalidMetadata; }
    }

    private static bool V020RarFixedContent(IReadOnlyList<byte[]> volumes, string password, byte[] plaintext,
        bool requireEncryptedHeader = false)
    {
        MemoryStream[] sources = volumes.Select(bytes => new MemoryStream(bytes, writable: false)).ToArray();
        try
        {
            ArchiveRarIntegrityIndex index = ArchiveIntegrity.InspectRarHeaders(sources, password, new());
            using IReader reader = index.OpenReader(password);
            bool passed;
            try
            {
                if (!reader.MoveToNextEntry()) throw new InvalidOperationException("RAR4 固定向量缺少成员。");
                using ArchiveIntegrityRarVerifier verifier = ArchiveIntegrity.BeginRar(reader.Entry, index, password);
                using EntryStream decoded = reader.OpenEntryStream();
                using MemoryStream bytes = new();
                using Crc32Stream crc = new(bytes);
                try
                {
                    decoded.CopyTo(crc);
                    verifier.Complete(decoded, bytes.Length, crc.Crc);
                    passed = verifier.Requirement.CanValidatePassword && bytes.ToArray().SequenceEqual(plaintext) &&
                        (!requireEncryptedHeader || index.HeaderEncrypted);
                }
                catch { reader.Cancel(); throw; }
                passed &= !reader.MoveToNextEntry();
            }
            catch { reader.Cancel(); throw; }
            return passed;
        }
        finally { foreach (MemoryStream source in sources) source.Dispose(); }
    }
}
